In [2]:
#NORMALIZATION PROBLEM
import numpy as np

#Create a random 5x5 ndarray
X = np.random.rand(5,5) #Creates a 5x5 array with random values between 0 and 1

#Normalize X using the formula Z = (X - mean)/std
#Calculate element-wise mean and standard deviation
mean = X.mean() #Mean of each column
std = X.std() #Standard Deviation of each column

#Apply the normalization formula
X_normalized = (X - mean) / std

#Save the normalized array as X_normalized.npy
np.save("X_normalized.npy", X_normalized)

In [3]:
print("Original Array (X):\n", X)

Original Array (X):
 [[0.98946835 0.04223551 0.09527599 0.44676407 0.46354061]
 [0.28120754 0.14190067 0.82007301 0.66785664 0.44408923]
 [0.40461943 0.78314857 0.75273697 0.39933413 0.65330528]
 [0.45616813 0.49663693 0.82064797 0.70536536 0.91419355]
 [0.65547018 0.23113441 0.78964975 0.58734979 0.59638736]]


In [6]:
print("\nMean:", mean)


Mean: 0.5455423772370197


In [7]:
print("Standard Deviation:", std)

Standard Deviation: 0.25120767175965864


In [8]:
print("\nNormalized Array (X_normalized):\n", X_normalized)


Normalized Array (X_normalized):
 [[ 1.76716724 -2.00354897 -1.79240699 -0.39321374 -0.32643018]
 [-1.05225621 -1.60680485  1.09284334  0.48690495 -0.40386168]
 [-0.56098186  0.94585564  0.82479405 -0.58202142  0.42897934]
 [-0.35577832 -0.19468136  1.09513212  0.63621858  1.4675156 ]
 [ 0.43759733 -1.25158584  0.97173534  0.16642568  0.20240221]]


In [12]:
#DIVISIBLE BY 3 PROBLEM
import numpy as np

#Create a 10x10 ndarray with squares of the first 100 positive integers (1-100)
#Create an array of integers from 1 to 100
integers = np.arange(1, 101)

#Square each integer
squares = integers ** 2

#Reshape into a 10x10 array
A = squares.reshape(10, 10)

#Find elements divisible by 3
#Extract elements that are divisible by 3
div_by_3 = A[A % 3 == 0]

#Save the result as div_by_3.npy
np.save("div_by_3.npy", div_by_3)

In [13]:
print("10x10 Array A:\n", A)

10x10 Array A:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [15]:
print("\nElements divisible by 3:\n", div_by_3)


Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
